// gp-page-v3.2-es5.js — version complète compatible ES5
// ------------------------------------------------------------
// - Strict équivalence avec la v3.1, mais ajout :
//   • Colonne "Lap" dans FL (lecture lap_release / lap_number…)
//   • Colonne "Total Laps (Q1–Q4)" dans GRID (backend ou fallback)
// - Aucune syntaxe ES6 (pas de =>, const, let, etc.)
// - Compatible Webador / anciens moteurs JavaScript

(function(){
  'use strict';

  /* ========================== Utils ========================== */
  function qs(sel,root){return(root||document).querySelector(sel);}
  function qsa(sel,root){return(root||document).querySelectorAll(sel);}
  function isNum(x){return x!==null&&x!==''&&!isNaN(x);}
  function getURLParam(k,d){try{var u=new URL(window.location.href);var v=u.searchParams.get(k);return v===null?d:v;}catch(e){return d;}}
  function fmtMs(v){if(v==null||isNaN(+v))return v;var ms=+v,s=Math.floor(ms/1000),mm=Math.floor(s/60),ss=s%60,mmm=ms%1000;return mm+':'+String(ss).padStart(2,'0')+'.'+String(mmm).padStart(3,'0');}
  function pick(o,keys){if(!o)return null;for(var i=0;i<keys.length;i++){var k=keys[i];if(o[k]!=null&&o[k]!=='')return o[k];}return null;}
  function clone(o){var r={};for(var k in o){r[k]=o[k];}return r;}
  function tryParseJSON(t,u){try{return JSON.parse(t);}catch(e){throw new Error('Invalid JSON at '+u+' — '+t.slice(0,120));}}
  function loadJSONwithFallback(urls){var i=0;function step(){if(i>=urls.length)return Promise.reject(new Error('All sources failed for '+urls[0]));var u=urls[i++];return fetch(u,{cache:'no-store'}).then(function(r){return r.text().then(function(t){if(!r.ok)throw new Error('HTTP '+r.status+' on '+u+' — '+t.slice(0,120));return tryParseJSON(t,u);});}).catch(function(){return step();});}return step();}

  /* ========================== Lookups ========================== */
  var DRIVERS=null,PARTICIPANTS=null;
  function loadDrivers(base){return fetch(base+'/lookups/drivers.min.json',{cache:'no-store'}).then(function(r){return r.json();}).then(function(j){DRIVERS=j;});}
  function loadParticipants(base){return fetch(base+'/lookups/participants.json',{cache:'no-store'}).then(function(r){return r.json();}).then(function(j){PARTICIPANTS=j;});}
  function driverName(id){if(id==null)return'';var k=String(id);return DRIVERS&&DRIVERS[k]?DRIVERS[k]:String(id);}
  function pinfo(raceId,driverId){if(!PARTICIPANTS)return{};var rn=PARTICIPANTS[String(raceId)]||{};return rn[String(driverId)]||{};}

  /* ========================== DOM & state ========================== */
  var app=qs('#f1-gp-app'),titleEl=qs('#gpTitle',app),statusEl=qs('#status',app),tabsEl=qs('#sessionTabs',app),tableBox=qs('#sessionTable',app);
  var COLORS={orange:'#ee5a2f',green:'#188038',blue:'#1a73e8',purple:'#6A32A8'};
  var STATIC_TABS=['EL1','EL2','EL3','EL4','WUP','PQ1','PQ2','SQ1','SQ2','SQ3','Q1','Q2','Q3','Q4','GRID','LPBLP','TLAPS','FL','LEAD','RACE','RESUME'];
  var state={raceId:null,meta:null,jsonRoot:null,sessions:[],sessionCode:null,rows:[],sort:{key:'pos',dir:1},columns:['pos','no','driver','car_engine','laps','time','gap_reason']};
  function info(m){if(statusEl){statusEl.textContent=m;statusEl.style.color='#666';}}function error(m){if(statusEl){statusEl.textContent=m;statusEl.style.color='#b00';}}

  /* ========================== Table ========================== */
  function toPos(r){var v=r.pos!=null?r.pos:(r.position!=null?r.position:0);v=Number(v);return isFinite(v)?v:0;}
  function cmpPos(a,b){var pa=toPos(a),pb=toPos(b);if(pa>0&&pb>0)return pa-pb;var la=Number(a.laps)||0,lb=Number(b.laps)||0;if(la!==lb)return lb-la;return 0;}
  function sortRows(){var k=state.sort.key,dir=state.sort.dir;if(k==='pos'){state.rows.sort(dir===1?cmpPos:function(a,b){return cmpPos(b,a);});return;}var num=state.rows.some(function(r){return isNum(r[k]);});state.rows.sort(function(a,b){var va=a[k],vb=b[k];if(num){var na=Number(va),nb=Number(vb);if(isNaN(na)&&isNaN(nb))return 0;if(isNaN(na))return 1;if(isNaN(nb))return-1;return(na-nb)*dir;}var sa=(va==null?'':String(va)).toLowerCase(),sb=(vb==null?'':String(vb)).toLowerCase();return sa.localeCompare(sb)*dir;});}
  function drawTable(){tableBox.innerHTML='';var tbl=document.createElement('table');tbl.style.width='100%';tbl.style.borderCollapse='collapse';tbl.style.fontSize='14px';tbl.style.background='#fff';tbl.style.boxShadow='0 1px 2px rgba(0,0,0,0.06)';tbl.style.borderRadius='12px';tbl.style.overflow='hidden';var thead=document.createElement('thead');thead.style.position='sticky';thead.style.top='0';thead.style.background='#fafafa';var trh=document.createElement('tr');var HEAD_MAP={pos:'Pos',no:'No',driver:'Driver',car_engine:'Car / Engine',laps:'Laps',time:'Time',gap_reason:'Gap / Reason',total_laps_q:'Total Laps (Q1–Q4)',lap:'Lap'};for(var i=0;i<state.columns.length;i++){(function(cn){var th=document.createElement('th');th.textContent=HEAD_MAP[cn]||cn;th.style.textAlign='left';th.style.padding='10px';th.style.borderBottom='1px solid #eee';th.style.cursor='pointer';th.onmousedown=function(e){e.preventDefault();};th.onclick=function(){if(state.sort.key===cn){state.sort.dir*=-1;}else{state.sort.key=cn;state.sort.dir=1;}sortRows();drawTable();};if(state.sort.key===cn){th.textContent+=' '+(state.sort.dir===1?'↑':'↓');}trh.appendChild(th);})(state.columns[i]);}thead.appendChild(trh);tbl.appendChild(thead);sortRows();var tbody=document.createElement('tbody');for(var r=0;r<state.rows.length;r++){var row=state.rows[r],tr=document.createElement('tr');tr.onmouseenter=function(){this.style.background='#fcfcfd';};tr.onmouseleave=function(){this.style.background='';};for(var c=0;c<state.columns.length;c++){var k=state.columns[c],td=document.createElement('td'),v=row[k];if(k==='pos'){var n=Number(v);v=(isFinite(n)&&n>0)?n:'—';}td.textContent=(v==null?'':v);td.style.padding='8px 10px';td.style.borderBottom='1px solid #f3f3f3';tr.appendChild(td);}tbody.appendChild(tr);}tbl.appendChild(tbody);tableBox.appendChild(tbl);}

  /* ========================== Sessions ========================== */
  function msFromRow(r){var m=pick(r,['best_lap_ms','best_ms','lap_ms','time_ms','milliseconds']);var n=Number(m);return isFinite(n)?n:null;}
  function buildDisplayRows(rows,sessionCode,raceId){if(!Array.isArray(rows))return[];var c=String(sessionCode||'').toUpperCase(),isRace=(c==='COURSE'||c==='RACE');var bestMs=null;if(!isRace){for(var i=0;i<rows.length;i++){var ms=msFromRow(rows[i]);if(ms!=null)bestMs=(bestMs==null||ms<bestMs)?ms:bestMs;}}var out=[],lapKeys=['laps','lap_count','nb_laps'];for(var j=0;j<rows.length;j++){var r=rows[j],drvId=pick(r,['driver_id','DriverId','driverId']),pin=pinfo(raceId,drvId);var pos=pick(r,['position','pos','rank']),team=pick(r,['team','team_name'])||pin.team||'',motor=pick(r,['engine','motor_name'])||pin.motor||'',num=pick(r,['num','number','no'])||pin.num_car||'';var laps=pick(r,lapKeys);if(/^Q[1-4]$/i.test(c)||c==='GRID'||c==='FL'){laps='';}var timeDisplay='',gapReason='';if(!isRace){var ms2=msFromRow(r);var timeRw=pick(r,['best_lap_time_raw','time_raw']);timeDisplay=timeRw||(ms2!=null?fmtMs(ms2):'');if(ms2!=null&&bestMs!=null&&ms2>bestMs){gapReason='+'+fmtMs(ms2-bestMs);}}else{var delta=pick(r,['delta','gap','status','reason']);if(delta&&delta.trim().charAt(0)==='+')gapReason=delta;if(delta){if(/[:smh]/.test(delta))timeDisplay=delta;else gapReason=delta;}}var lapNum=pick(r,['lap_number','lap','lap_no','lapNumber','lap_release']);out.push({pos:(pos!=null?Number(pos):null),no:String(num||''),driver:driverName(drvId),car_engine:team+(motor?('/'+motor):''),laps:(laps===''||laps==null)?'':Number(laps),lap:lapNum||'',time:timeDisplay,gap_reason:gapReason,driver_id:drvId||null});}if(!isRace){var order=rows.map(function(r,i){return{i:i,ms:msFromRow(r)};});order.sort(function(a,b){if(a.ms==null&&b.ms==null)return 0;if(a.ms==null)return 1;if(b.ms==null)return-1;return a.ms-b.ms;});var rk=1;for(var k=0;k<order.length;k++){var o=order[k],row=out[o.i];if(!row.pos)row.pos=(o.ms==null?null:rk++);}}return out;}
  function computeTotalQualLapsByDriver(allSessions){var qCodes=['Q1','Q2','Q3','Q4'],totalByDriver={};for(var qi=0;qi<qCodes.length;qi++){var s=null;for(var si=0;si<allSessions.length;si++){if(allSessions[si].code===qCodes[qi]){s=allSessions[si];break;}}if(!s||!Array.isArray(s.rows))continue;for(var ri=0;ri<s.rows.length;ri++){var r=s.rows[ri];var id=pick(r,['driver_id','DriverId','driverId']);if(id==null)continue;var laps=Number(pick(r,['laps','lap_count','nb_laps']))||0;totalByDriver[String(id)]=(totalByDriver[String(id)]||0)+laps;}}return totalByDriver;}
  function findSession(code){var C=String(code).toUpperCase();for(var i=0;i<state.sessions.length;i++){var sc=state.sessions[i].code;if(sc===C)return state.sessions[i];if(C==='COURSE'&&sc==='RACE')return state.sessions[i];}return null;}
  function loadSessionRows(){var sess=findSession(state.sessionCode);if(!sess){state.rows=[];tableBox.innerHTML='';info('No data for '+state.sessionCode);return;}var src=Array.isArray(sess.rows)?sess.rows:(Array.isArray(sess.data)?sess.data:[]),withNames=[];for(var i=0;i<src.length;i++){var r=src[i],o=clone(r),id=pick(r,['driver_id','DriverId','driverId']);o.driver=driverName(id);withNames.push(o);}state.rows=buildDisplayRows(withNames,state.sessionCode,state.raceId);var c=String(state.sessionCode||'').toUpperCase();if(/^Q[1-4]$/.test(c)){state.columns=['pos','no','driver','car_engine','time','gap_reason'];}else if(c==='GRID'){var anyBackend=false;for(var j=0;j<state.rows.length;j++){if('total_laps_q1q4' in src[j]){state.rows[j].total_laps_q=src[j].total_laps_q1q4;anyBackend=true;}}if(!anyBackend){var totals=computeTotalQualLapsByDriver(state.sessions);for(var k=0;k<state.rows.length;k++){var did=state.rows[k].driver_id;state.rows[k].total_laps_q=totals[String(did)]||0;}}state.columns=['pos','no','driver','car_engine','total_laps_q','time','gap_reason'];}else if(c==='FL'){state.columns=['pos','no','driver','car_engine','lap','time','gap_reason'];}else{state.columns=['pos','no','driver','car_engine','laps','time','gap_reason'];}state.sort={key:'pos',dir:1};info('Session '+c+' • '+src.length+' rows');drawTable();}

  /* ========================== Init ========================== */
  function init(){state.raceId=Number(getURLParam('race',null));state.sessionCode=(getURLParam('session','')||'RACE').toUpperCase();if(!state.raceId){info('Missing ?race=');return;}var repo='menditeguy/f1data-races-1-500';if(state.raceId>500&&state.raceId<=1000)repo='menditeguy/f1data-races-501-1000';else if(state.raceId>1000)repo='menditeguy/f1data-races-1001-1500';var base=(app&&app.dataset&&app.dataset.base)?app.dataset.base:'https://menditeguy.github.io/f1datadrive-data';var path='/races/'+state.raceId+'/sessions.json';var sources=['https://cdn.jsdelivr.net/gh/'+repo+'@main'+path,'https://cdn.statically.io/gh/'+repo+'/main'+path,'https://rawcdn.githack.com/'+repo+'/main'+path'];Promise.all([loadDrivers(base),loadParticipants(base)]).then(function(){return loadJSONwithFallback(sources);}).then(function(json){state.jsonRoot=json;state.meta=(json&&json.meta)?json.meta:{};var sessions=[];if(Array.isArray(json.sessions)){for(var i=0;i<json.sessions.length;i++){var sx=json.sessions[i];var code=(sx.code||sx.session||'UNK').toUpperCase();if(code==='MT')code='FL';if(code==='GRILLE'||code==='STARTING_GRID')code='GRID';if(code==='RESULTS_RACE'||code==='COURSE')code='RACE';sessions.push({code:code,rows:sx.rows||sx.data||[]});}}state.sessions=sessions;if(!findSession(state.sessionCode)){state.sessionCode='RACE';}loadSessionRows();}).catch(function(e){error('Load error '+e);});}
  if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}
})();